# Target specific macros
TARGET = esteira

TARGET_CPP_SOURCES = esteira.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./esteira.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../../ecrobot/ecrobot++.mak
