# Target specific macros
TARGET = braco

TARGET_CPP_SOURCES = braco.cpp
	
TOPPERS_OSEK_OIL_SOURCE = ./braco.oil

# Don't modify below part
O_PATH ?= build

# makefile for C++(.cpp) build
include ../../ecrobot/ecrobot++.mak
